version: '3.8'

services:
  # Frontend - Production Build
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: work-util-frontend-prod
    environment:
      - REACT_APP_API_URL=/api
    networks:
      - work-util-network

  # Backend - Production
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: work-util-backend-prod
    environment:
      - SECRET_KEY=${SECRET_KEY:-your-production-secret-key}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - DATABASE_URL=sqlite:///./data/app.db
    volumes:
      - backend_data:/app/data
    networks:
      - work-util-network

  # Nginx - Production
  nginx:
    image: nginx:alpine
    container_name: work-util-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - work-util-network

volumes:
  backend_data:
    driver: local

networks:
  work-util-network:
    driver: bridge