version: '3.8'

services:
  # Frontend - React 애플리케이션
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: work-util-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - work-util-network

  # Backend - FastAPI 애플리케이션
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: work-util-backend
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=your-production-secret-key-change-this
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - DATABASE_URL=sqlite:///./app.db
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    networks:
      - work-util-network

  # Nginx - 리버스 프록시
  nginx:
    image: nginx:alpine
    container_name: work-util-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - work-util-network

volumes:
  backend_data:
    driver: local

networks:
  work-util-network:
    driver: bridge